### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by sivkun** [liangklfangl/webpack-hmr#1]
你好，我从这  http://blog.csdn.net/liangklfang/article/details/56848925  过来的。我想请教一个问题，我参考这里  https://doc.webpack-china.org/guides/hot-module-replacement/  ，实现HMR，但是修改文件内容是总是会刷新页面，而不是局部刷新，不知道是什么原因。
package.json启动脚本
 `"start": "node ./node_modules/webpack-dev-server/bin/webpack-dev-server.js --config ./config/webpack.config.dev.js"`或者`webpack-dev-server --config ./config/webpack.config.dev.js`效果一样。页面总是刷新。
谢谢！

**Comment by liangklfang** [comment]
可以看看[我这里](https://github.com/liangklfangl/wcf)是怎么兼容的，我当时也发现了这个问题，然后做了一个hack,你可以运行这个例子的test目录看看效果。@sivkun
